# Generated by Django 2.2.2 on 2019-07-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatarUrl',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='language',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickName',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phonenumber',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
