# Generated by Django 2.2.2 on 2019-07-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0002_auto_20190715_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatarUrl',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
